controller_list:
  - name: fake_barrett_hand_controller
    joints:
      - finger_1_prox_joint
      - finger_1_med_joint
      - finger_2_prox_joint
      - finger_2_med_joint
      - finger_3_med_joint
  - name: fake_ur5_arm_controller
    joints:
      - urshoulder_pan_joint
      - urshoulder_lift_joint
      - urelbow_joint
      - urwrist_1_joint
      - urwrist_2_joint
      - urwrist_3_joint