controller_list:
  - name: ur5_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - urshoulder_pan_joint
      - urshoulder_lift_joint
      - urelbow_joint
      - urwrist_1_joint
      - urwrist_2_joint
      - urwrist_3_joint
  - name: barrett_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - finger_1_prox_joint
      - finger_1_med_joint
      - finger_2_prox_joint
      - finger_2_med_joint
      - finger_3_med_joint